### PR TITLE
WIP: Rewrite

### PR DESCRIPTION
**Pull request by kaedroho**
This rewrite will bring the following:

 - A new frontend commenting UI
 - The ability to share with external users without formal review
 - See comments in the admin
 - Headless support

TODO:
 - [x] Add new models
 - [x] Remove old models with data migrations to new models
 - [x] Add new commenting API
 - [x] Add new commenting frontend (https://github.com/wagtail/wagtail-review-ui)
 - [x] Add share modal
 - [x] Add comments viewer in editor
 - [x] Make review URL configurable (for headless sites)
 - [ ] Custom `ReviewRequest` classes (using MTI instead of swappable models) (https://github.com/wagtail/wagtail-review/pull/14)
 - [ ] Review response emails

### CODE REVIEW

**Comment by kaedroho** [comment]
Test coverage at 96% now :tada:

**Comment by mikemonteith** [comment]
@kaedroho has this work been abandoned now? We are interested in picking up this plugin again.

**Comment by kaedroho** [comment]
Hey @mikemonteith 

@jacobtoppm is currently working on integrating this branch with Wagtail's new Workflow feature (coming hopefully 2.9). That'll be a breaking change so we thought we'd ship that at the same time as this.

After wagtail-localize and the React Page chooser model, styling this branch is next on my list. Should get round to it around late February/March I think. After that this should be ready to go!

**Comment by mikemonteith** [comment]
That's interesting! Is there anywhere we can see this new workflow feature, or a roadmap or something?
Workflow is something we are about to start working on internally at nhs.uk. It's something that has come up a few times before but never went very far.

**Comment by kaedroho** [comment]
> Is there anywhere we can see this new workflow feature, or a roadmap or something?

There's an RFC for it here: https://github.com/wagtail/rfcs/blob/workflow/text/045-workflow.md

Current progress on this branch: https://github.com/jacobtoppm/wagtail/tree/workflow-base

**Comment by gasman** [comment]
@mikemonteith As an update to the above, workflow feature development is now happening on a branch on the main Wagtail repo - https://github.com/wagtail/wagtail/tree/feature/workflow

**Pull request merged**
